-- Moved to 20260904210000_harden_rpc_and_profile_access_replay.sql (6 Sep 2026): this file sorted
-- before the migrations that create the functions it alters, so a fresh database could not replay.
-- Kept as an empty file so production's migration history (which recorded this version) stays valid.
